
from rest_framework import serializers
from .models import Document

class DocumentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Document
        fields = ['id', 'uploaded_file', 'simplified_text', 'uploaded_at']
        read_only_fields = ['simplified_text', 'uploaded_at'] # These are generated by the server